databases:
  - name: DjangoPostdb
    plan: free
    databaseName: DjangoPost
    user: DjangoPost

services:
  - type: web
    plan: free
    name: DjangoPost
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd dj_ajax/src && python -m gunicorn posts_proj.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DjangoPostdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4